"1":
  brasil:
    - Rio de Janeiro
    - Florianopolis
    - Fernando de Noronha
    - Salvador
    - Maceio
    - Porto de Galinhas
  exterior:
    - Cancun
    - Punta Cana
    - Aruba
    - Miami
    - Dubai
    - Phuket
    - Krabi
    - Alpes
    - Sydney
"2":
  brasil:
    - Salvador
    - Rio de Janeiro
    - Recife
    - Olinda
    - Trancoso
    - Praia dos Carneiros
    - Ilhabela
  exterior:
    - Veneza
    - Caribe
    - Tailandia
    - Maldivas
    - Sri Lanka
    - Riviera Maya
"3":
  brasil:
    - Gramado
    - Vale dos Vinhedos
    - Chapada Diamantina
    - Rio de Janeiro
    - Ubatuba
    - Ilhabela
    - Curitiba
    - Morretes
    - Jalapao
  exterior:
    - Japao
    - Marrocos
    - Lisboa
    - Porto
    - Andaluzia
    - Vietna
    - Cusco
    - Valle Sagrado
"4":
  brasil:
    - Tiradentes
    - Ouro Preto
    - Chapada dos Veadeiros
    - Petropolis
    - Serra do Cipo
    - Foz do Iguacu
  exterior:
    - Holanda
    - Japao
    - Roma
    - Florenca
    - Grecia
    - Istambul
    - Capadocia
    - Paris
    - Provence
"5":
  brasil:
    - Bonito
    - Pantanal
    - Campos do Jordao
    - Chapada dos Veadeiros
    - Jericoacoara
    - Canela
    - Gramado
  exterior:
    - Italia
    - Espanha
    - Portugal
    - Costa Rica
    - Peru
    - California
"6":
  brasil:
    - Campina Grande
    - Caruaru
    - Campos do Jordao
    - Serra do Rio do Rastro
    - Chapada Diamantina
    - Jalapao
  exterior:
    - Islandia
    - Noruega
    - Canada
    - Escocia
    - Croacia
    - Bali
"7":
  brasil:
    - Gramado
    - Canela
    - Campos do Jordao
    - Foz do Iguacu
    - Chapada Diamantina
    - Lencois Maranhenses
    - Abrolhos
  exterior:
    - Portugal
    - Espanha
    - Franca
    - Italia
    - Bariloche
    - Africa do Sul
"8":
  brasil:
    - Lencois Maranhenses
    - Bonito
    - Pantanal
    - Jericoacoara
    - Chapada dos Veadeiros
    - Chapada Diamantina
  exterior:
    - Peru
    - Salar de Uyuni
    - Bali
    - Quenia
    - Tanzania
    - Grecia
    - Rocosas
"9":
  brasil:
    - Pantanal
    - Bonito
    - Chapada dos Veadeiros
    - Serra Gaucha
    - Jalapao
    - Fernando de Noronha
  exterior:
    - Islandia
    - Noruega
    - Italia
    - Grecia
    - Canada
    - Japao
"10":
  brasil:
    - Blumenau
    - Fernando de Noronha
    - Chapada dos Veadeiros
    - Paraty
    - Bonito
    - Jericoacoara
  exterior:
    - Nova Inglaterra
    - Canada
    - Baviera
    - Marrocos
    - Egito
    - Mexico
"11":
  brasil:
    - Abrolhos
    - Jericoacoara
    - Maceio
    - Porto de Galinhas
    - Rio de Janeiro
    - Fernando de Noronha
  exterior:
    - Islandia
    - Noruega
    - Alemanha
    - Austria
    - Tailandia
    - Vietna
    - Nova York
"12":
  brasil:
    - Rio de Janeiro
    - Salvador
    - Florianopolis
    - Maceio
    - Natal
    - Fernando de Noronha
  exterior:
    - Caribe
    - Nova York
    - Paris
    - Londres
    - Dubai
    - Alpes
    - Riviera Maya
